package com.telegram.ia.telegramlink.domain.model;

public enum TelegramLinkEventType {
    INVITATION_CREATED,
    INVITATION_REVOKED,
    INVITATION_EXPIRED,
    TOKEN_VALIDATION_STARTED,
    TOKEN_VALIDATION_FAILED,
    CLIENT_TELEGRAM_LINKED,
    CLIENT_TELEGRAM_UNLINKED,
    DUPLICATE_TELEGRAM_ACCOUNT_DETECTED
}
